
production:
  adapter: postgresql
  database: redmine
  host: localhost
  username: postgres
  password: vesper
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_development
  host: localhost
  username: postgres
  password: vesper
  encoding: utf8

test:
  adapter: postgresql
  database: redmine_test
  host: localhost
  username: postgres
  password: vesper
  encoding: utf8

